# Site settings
title: Emerson Soares
email: on.emersonsoares@gmail.com
author: Emerson Soares
description: "Um pouco sobre tudo"
baseurl: ""
url: "http://emersonsoares.github.io"
google_analytics:
animated: false

# Build settings
markdown: redcarpet
permalink: pretty
paginate: 3
pygments: true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments:
	linespans: "line"